Fixed Name Extraction Issues, License Update
ubccr/simplesamlphp-module-authglobus pull request #8
Opened 2018-09-06 18:14 UTC by chakrabortyr

## Description
The method getFullName did not properly delimit on whitespace names prior to this change. Migrated from GPL 3.0 to LGPL 3.0.

## Motivation and Context
Bug fix, we also don't want to hamstring users of the Globus platform who want to use this module with the GPL

## Tests performed
Manual inputs to getFullName function.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-09-06 18:18 UTC, plessbd commented
The license should be changed in a different pull request.

Is there a PR in any of the xdmod repos to upgrade to the new version?

2018-09-06 18:34 UTC, plessbd requested changes
Move license change to a different PR, Add more detailed testing notes, Open PR's in related repos with updated module version

2018-09-07 15:04 UTC, plessbd submitted a review, later dismissed

2018-09-07 15:04 UTC, plessbd commented on lib/Auth/Source/Globus.php
>      protected function getFullName($name) {
this seems overly complicated compared to something like this:
```php
function getFullName($name){
    $trimmedName = trim($name);
    $lastName = 'UNKNOWN';
    $firstName = 'UNKNOWN';
    if(strpos($trimmedName, ',') !== false ){
        list($lastName, $firstName) = explode(',', $trimmedName, 2);
    }
    else if(strpos($trimmedName, ' ') !== false ){
        list($firstName, $lastName) = explode(' ', $trimmedName, 2);
    }
    return array(
        'first_name' => trim($firstName),
        'last_name' => trim($lastName)
    );
}
```

old:
```
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => 
    [last_name] => 
)
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => First
    [last_name] => Last
)
Array
(
    [first_name] => First
    [last_name] => Middle Last
)
Array
(
    [first_name] => First
    [last_name] => von Last
)
Array
(
    [first_name] => First
    [last_name] => M. Last
)
Array
(
    [first_name] => First
    [last_name] => M. von Last
)
Array
(
    [first_name] => First
    [last_name] => Last
)
Array
(
    [first_name] => First Middle
    [last_name] => Last
)
Array
(
    [first_name] => First
    [last_name] => von Last
)
Array
(
    [first_name] => First M.
    [last_name] => Last
)
Array
(
    [first_name] => First M.
    [last_name] => von Last
)
```
new:
```
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => 
    [last_name] => 
)
Array
(
    [first_name] => UNKNOWN
    [last_name] => UNKNOWN
)
Array
(
    [first_name] => First
    [last_name] => Last
)
Array
(
    [first_name] => First
    [last_name] => Middle Last
)
Array
(
    [first_name] => First
    [last_name] => von Last
)
Array
(
    [first_name] => First
    [last_name] => M. Last
)
Array
(
    [first_name] => First
    [last_name] => M. von Last
)
Array
(
    [first_name] => First
    [last_name] => Last
)
Array
(
    [first_name] => First Middle
    [last_name] => Last
)
Array
(
    [first_name] => First
    [last_name] => von Last
)
Array
(
    [first_name] => First M.
    [last_name] => Last
)
Array
(
    [first_name] => First M.
    [last_name] => von Last
)
```

2018-09-07 15:04 UTC, plessbd commented on lib/Auth/Source/Globus.php
> +            $delimiter = strpos($name, ',') !== false ? ',' : ' ';
this should use `$trimmedName` instead of `$name`

2018-09-07 15:04 UTC, plessbd commented on lib/Auth/Source/Globus.php
> +        /*
this doesnt need to be in the code, this should be a unit test, but could just be a comment on the PR

2018-09-07 18:57 UTC, plessbd commented
fix your errors

2018-09-07 19:27 UTC, jpwhite4 approved these changes
I begrudgingly approve

2018-09-07 19:36 UTC, merged